package.path="./?.lua;"..package.path
local Game=require("src.Game")
local Storage=require("src.Storage")
local App=require("src.App")
local Catalog=require("src.Catalog")
local passed,failed=0,0
local function eq(a,b) assert(a==b,tostring(a).." ~= "..tostring(b)) end
local function test(name,fn)
    local ok,err=pcall(fn)
    if ok then passed=passed+1; print("PASS "..name) else failed=failed+1; print("FAIL "..name..": "..err) end
end
local function starter()
    local g=Game.new(191); assert(g:buyMaster("moon")); return g
end
local function advance(g,stop)
    for _=1,10000 do
        if g.phase==stop or g.phase=="failed" then return end
        if g.phase=="swap" then assert(g:loadMedia(g.swapDrive,g.swapMedia))
        elseif g.phase=="blocked" then
            local code=g:protectionError(g.selected)
            if code then
                g:setConfig("mode",g.job.mode); g:setConfig("sync",g.job.sync); g:setConfig("length",g.job.length)
            end
            g:retry()
            if g.repair then g:update(g.repair.center*g.repair.period,false); g:hit() end
        else g:update(0.1,false) end
    end
    error("operation did not reach "..stop.."; phase="..g.phase)
end
local function finish(g)
    advance(g,"complete"); eq(g.phase,"complete"); assert(g:verify()); advance(g,"complete"); assert(g.verified)
end
local function prepare(id)
    local _,p=Storage.defaults(); p.money=9999; p.completed=20
    local g=Game.new(19,p); g:buyMaster(id)
    g:setConfig("first",g.job.first); g:setConfig("last",g.job.last); g:setConfig("side",g.job.side)
    return g
end

test("starts with one drive, 512 KB and affordable first master",function()
    local g=Game.new(1); eq(g.profile.drives,1); eq(g.profile.ram,512); eq(g:capacity(),81)
    assert(g:buyMaster("moon")); eq(g.profile.money,30); eq(g.slots[0],"source")
end)
test("full single-drive 512 KB disk requires three media swaps",function()
    local g=starter(); g:start(); advance(g,"complete")
    eq(g.swaps,3); eq(g.profile.blanks,2); eq(g.position,161)
    for i=1,160 do eq(g.tracks[i],"good") end
end)
test("buffer is bounded and read is not yet a written copy",function()
    local g=starter(); g:start(); g:update(20,false)
    eq(g.phase,"swap"); eq(#g.buffer,81); eq(g.swapMedia,"blank")
    eq(g.tracks[1],"buffer"); eq(g.verified,false)
end)
test("wrong disk or drive cannot satisfy swap request",function()
    local g=starter(); g:start(); g:update(20,false)
    eq(g:loadMedia(0,"source"),false); eq(g.phase,"swap")
    eq(g:loadMedia(1,"blank"),false); eq(g.phase,"swap")
end)
test("one blank is consumed across multiple write batches",function()
    local g=starter(); local count=g.profile.blanks; g:start(); finish(g); eq(g.profile.blanks,count-1)
end)
test("1024 KB buffers full standard disk with one swap",function()
    local g=starter(); g.profile.ram=1024; g:start(); finish(g); eq(g.swaps,1); assert(g.cache)
end)
test("long tracks need more memory than standard tracks",function()
    local g=starter(); g.profile.ram=1024
    eq(g:capacity(),174); g:setConfig("length","LONG"); eq(g:capacity(),153)
    g:start(); finish(g); eq(g.swaps,3); eq(g.cache,nil)
end)
test("external drive avoids alternating source and destination swaps",function()
    local g=starter(); g.profile.drives=2; assert(g:setDrive("target",1)); g:start(); finish(g)
    eq(g.swaps,1); eq(g.dual,true); eq(g.slots[0],"source"); eq(g.slots[1],"blank")
end)
test("source and destination routing really controls required media",function()
    local g=starter(); g.profile.drives=3
    g:setDrive("source",2); g:setDrive("target",1); g:start()
    eq(g.phase,"swap"); eq(g.swapDrive,2); eq(g.swapMedia,"source")
end)
test("routing and track range cannot mutate an in-flight copy",function()
    local g=starter(); g:start(); eq(g:setDrive("source",0),false)
    eq(g:setConfig("last",20),false); eq(g.config.last,79)
end)
test("invalid range is rejected without taking a blank",function()
    local g=starter(); g:setConfig("first",50); g:setConfig("last",10)
    eq(g:start(),false); eq(g.profile.blanks,3)
end)
test("partial upper-side order writes only requested tracks",function()
    local g=prepare("ledger"); g:start(); finish(g)
    eq(#g.queue,28)
    for i=1,160 do eq(g.tracks[i],i>=13 and i<=40 and "good" or "skip") end
    assert(g:deliver())
end)
test("wrong range cannot be sold",function()
    local g=prepare("ledger"); g:defaults(); g:start(); advance(g,"complete"); g:verify(); advance(g,"complete")
    eq(g.verified,false); local cash=g.profile.money; eq(g:deliver(),false); eq(g.profile.money,cash)
end)
test("completed copy must be verified before payment",function()
    local g=starter(); g:start(); advance(g,"complete"); eq(g:deliver(),false)
    g:verify(); advance(g,"complete"); assert(g:deliver()); eq(g.profile.money,100)
end)
test("a delivered copy cannot be paid twice",function()
    local g=starter(); g:start(); finish(g); g:deliver(); local cash=g.profile.money
    eq(g:deliver(),false); eq(g.profile.money,cash)
end)
test("NOCHMAL repeats a sold copy and respects finite demand",function()
    local g=starter(); g:start(); finish(g); g:deliver()
    assert(g:repeatCopy()); finish(g); g:deliver(); eq(g:remaining(),0); eq(g:repeatCopy(),false)
end)
test("NOCHMAL reuses a full RAM image without reading source again",function()
    local g=starter(); g.profile.ram=1024; g:start(); finish(g); g:deliver()
    assert(g:repeatCopy()); eq(g.phase,"swap"); eq(g.afterSwap,"writing"); eq(#g.buffer,160)
    finish(g); eq(g.swaps,1)
end)
test("custom header halts until NIBBLE + NOCHMAL",function()
    local g=prepare("reef"); g:start(); advance(g,"blocked"); eq(g.tracks[g.selected],"5")
    eq(g:retry(),false); g:setConfig("mode","NIBBLE"); assert(g:retry()); eq(g.phase,"reading")
end)
test("sync mismatch needs the actual required sync word",function()
    local g=prepare("atlas"); g:start(); advance(g,"blocked"); eq(g.tracks[g.selected],"2")
    g:setConfig("sync","8914"); eq(g:retry(),false)
    g:setConfig("sync","A245"); assert(g:retry()); finish(g)
end)
test("long track requires both correct mode and track length",function()
    local g=prepare("castle"); g:setConfig("mode","NIBBLE"); g:start(); advance(g,"blocked")
    -- The first weak read may come before the protected track.
    if g.tracks[g.selected]=="6" then g:retry(); g:update(g.repair.center*g.repair.period,false); g:hit(); advance(g,"blocked") end
    eq(g.tracks[g.selected],"7"); g:setConfig("length","LONG"); assert(g:retry())
end)
test("weak-read calibration recovers error 6",function()
    local g=prepare("paint"); g:start(); advance(g,"blocked"); eq(g.tracks[g.selected],"6")
    g:retry(); assert(g.repair); g:update(g.repair.center*g.repair.period,false); g:hit()
    eq(g.health,5); eq(g.phase,"reading"); eq(g.combo,1)
end)
test("DOSCOPY+ corrects weak reads but does not bypass custom headers",function()
    local g=prepare("paint"); g:setConfig("mode","DOSCOPY+"); g:start(); advance(g,"swap")
    eq(g.phase,"swap"); eq(g.health,5)
    g=prepare("reef"); g:setConfig("mode","DOSCOPY+"); g:start(); advance(g,"blocked"); eq(g.tracks[g.selected],"5")
end)
test("five missed calibrations fail and repeat can restart",function()
    local g=prepare("paint"); g:start(); advance(g,"blocked")
    for _=1,5 do g:retry(); g:hit() end
    eq(g.phase,"failed"); assert(g:repeatCopy())
end)
test("purchases cannot overspend or install upgrades twice",function()
    local g=starter(); eq(g:buyUpgrade("ram1024"),false); eq(g.profile.money,30)
    g.profile.money=150; assert(g:buyUpgrade("ram1024")); eq(g.profile.money,30)
    eq(g:buyUpgrade("ram1024"),false); eq(g.profile.money,30)
end)
test("delivered jobs unlock disks and pay for hardware progression",function()
    local g=starter(); eq(g:buyMaster("reef"),false)
    for _=1,2 do g:start(); finish(g); g:deliver() end
    eq(g.profile.completed,2); eq(g.profile.money,170); assert(g:buyUpgrade("drive2"))
    eq(g.profile.drives,2); eq(g.target,1); eq(g.profile.money,10)
end)
test("buying owned master does not charge again",function()
    local g=starter(); local cash=g.profile.money; g:buyMaster("moon"); eq(g.profile.money,cash)
end)
test("pause and market stop the simulation without dropping buffer",function()
    local g=starter(); g:start(); g:update(2,false); local pos=g.position; local time=g.time
    g:togglePause(); g:update(30,true); eq(g.position,pos); eq(g.time,time); assert(#g.buffer>0)
end)
test("verification locks job switching and hardware installation",function()
    local g=starter(); g:start(); advance(g,"complete"); g:verify()
    eq(g:buyMaster("moon"),false); eq(g:buyUpgrade("drive2"),false)
end)
test("turbo accelerates, overheats, and recovers",function()
    local g=starter(); g.profile.drives=2; g.target=1; g:start(); g:loadMedia(1,"blank")
    g:update(4,true); assert(g.stall>0); local pos=g.position; g:update(0.5,false); eq(pos,g.position)
    g:update(2,false); eq(g.stall,0)
end)
test("native frame rate does not change copy progression",function()
    local a,b=starter(),starter(); a:start(); b:start()
    for _=1,60 do a:update(1/30,false) end
    for _=1,288 do b:update(1/144,false) end
    eq(a.position,b.position); eq(#a.buffer,#b.buffer)
end)
test("business save roundtrip and old score migration",function()
    local settings,p=Storage.defaults(); p.money=241; p.ram=1024; p.drives=2
    p.owned.reef=true; p.delivered.reef=1; p.selected="reef"; settings.music=false
    local s,q=Storage.decode(Storage.encode(settings,p)); eq(q.money,241); eq(q.ram,1024)
    eq(q.drives,2); eq(q.delivered.reef,1); eq(q.selected,"reef"); eq(s.music,false)
    s,q=Storage.decode("best=800\nmusic=0\nsfx=1\n"); eq(s.best,800); eq(q.ram,512); eq(q.money,40)
end)
test("save parser clamps invalid values without evaluating code",function()
    local _,p=Storage.decode("version=2\nmoney=-99\nram=999\ndrives=999\nselected=os.execute('x')\n")
    eq(p.money,0); eq(p.ram,512); eq(p.drives,4); eq(p.selected,nil)
end)
test("click actions change profile, media, routing and numeric inputs",function()
    local s,p=Storage.defaults(); local a=App.new(s,p,19)
    a:action("master","moon"); eq(a.page,"info")
    a:action("range"); a:action("edit","first"); a.editText="12"; a:applyEdit(); eq(a.game.config.first,12)
    a:action("side"); eq(a.game.config.side,"UPPER")
    a:action("defaults"); a:action("media",{index=0,media="source"}); eq(a.page,nil)
    a:action("start"); assert(a.game:busy()); a:action("pause"); eq(a.game.paused,true)
end)
test("all nine fictional orders can be completed and sold",function()
    for _,job in ipairs(Catalog.jobs) do
        local g=prepare(job.id); g:start(); finish(g); assert(g:deliver(),job.id)
    end
end)
test("routing to another source still requires a destination blank",function()
    local g=starter(); g.profile.drives=3; g:setDrive("source",2); g:setDrive("target",1)
    g:start(); g:loadMedia(2,"source"); eq(g.phase,"swap"); eq(g.swapDrive,1); eq(g.swapMedia,"blank")
    g:loadMedia(1,"blank"); finish(g); eq(g.profile.blanks,2)
end)
test("corrected protection profile is retained for cached repeats",function()
    local g=prepare("reef"); g.profile.ram=1024; g:start(); finish(g); g:deliver()
    eq(g.config.mode,"NIBBLE"); assert(g:repeatCopy()); eq(g.afterSwap,"writing"); eq(#g.buffer,160)
end)
test("new orders renew sold-out masters without duplicating past payouts",function()
    local g=starter()
    for _=1,2 do g:start(); finish(g); g:deliver() end
    local cash=g.profile.money; assert(g:renewOrders()); eq(g.profile.money,cash)
    eq(g:remaining(),2); eq(g.profile.completed,2); assert(g:repeatCopy())
end)
test("blank purchases preserve access to the first master after save reload",function()
    local settings,p=Storage.defaults(); settings,p=Storage.decode(Storage.encode(settings,p))
    local g=Game.new(19,p)
    for _=1,5 do assert(g:buyBlanks()) end
    eq(g.profile.money,10); eq(g:buyBlanks(),false); assert(g:buyMaster("moon"))
end)
print(string.format("\n%d passed / %d failed",passed,failed)); os.exit(failed==0 and 0 or 1)
